---

# Copy iptables rules script (making executable)
#
- name: Copy firewall rules script
  copy:
    mode: 0770
    owner: root
    group: root
    dest: /usr/local/bin/iptables-rules.sh
    src: iptables-rules.sh
    force: yes


# Copy firewall service definition
#
- name: Copy firewall service definition
  copy:
    mode: 0644
    owner: root
    group: root
    dest: /lib/systemd/system/iptables-rules.service
    src: iptables-rules.service
    force: yes


# Enable iptables rules service
#
- name: Enable firewall service
  service:
    name: iptables-rules.service
    enabled: yes
    state: started


# Create consul data directory
#
- name: Create consul data directory
  file:
    path: /var/consul
    state: directory
    mode: 0755


# Copy consul configuration file
#
- name: Copy consul configuration file
  template:
    mode: 0640
    owner: consul
    group: consul
    dest: /etc/consul.d/consul.hcl
    src: consul.hcl.j2
    force: yes


# Copy consul service definition
#
- name: Copy consul service definition
  copy:
    mode: 0644
    owner: root
    group: root
    dest: /lib/systemd/system/consul.service
    src: consul.service
    force: yes


# Enable consul service
#
- name: Enable consul service
  service:
    name: consul.service
    enabled: yes
    state: started

