---
# SPDX-FileCopyrightText: 2022 Wilfred Nicoll <xyzroller@rollyourown.xyz>
# SPDX-License-Identifier: GPL-3.0-or-later

# Set up HAProxy certs directory
#
- name: Create the `/etc/haproxy/ssl` directory
  file:
    path: /etc/haproxy/ssl/
    state: directory
    mode: 0755


# Copy HAProxy base configuration
#
- name: Copy haproxy base config file
  copy:
    mode: 0644
    owner: root
    group: root
    dest: /etc/haproxy/haproxy.cfg
    src: haproxy.cfg
    force: yes


# Add a cronjob to reload the HAProxy configuration every day
#
- name: Add haproxy reload cronjob
  cron:
    name: "haproxy reload"
    special_time: daily
    job: "systemctl reload haproxy"
    state: present


# Copy haproxy reload script
#
- name: Copy haproxy reload script
  copy:
    mode: 0770
    owner: root
    group: root
    dest: /usr/local/bin/reload-haproxy.sh
    src: reload-haproxy.sh
    force: yes


# Copy ingress-proxy consul service configuration file
#
- name: ingress-proxy consul service configuration file
  copy:
    mode: 0640
    owner: consul
    group: consul
    dest: /etc/consul.d/ingress-proxy-service.hcl
    src: ingress-proxy-service.hcl
    force: yes


# Copy haproxy log rotation and deletion configuration
#
- name: Copy haproxy log rotation and deletion configuration
  template:
    mode: 0644
    owner: root
    group: root
    dest: /etc/logrotate.d/haproxy
    src: logrotate_haproxy.j2
    force: yes
