---
## The generic directory /var/containers/{{ module_id }}
## for LXD container persistent storage must be created
## Further module-specific container directories should be
## added here
## -----------------------------------------------------------

## Directories for module-specific LXD container persistent storage
## -----------------------------------------------------------------

- name: Create a directory to mount in module containers
  file:
    path: "/var/containers/{{ module_id }}"
    state: directory
    mode: '0755'


## Copy README into top-level directory for module containers

- name: Copy README
  copy:
    mode: 0644
    owner: root
    group: root
    dest: "/var/containers/{{ module_id }}/README"
    src: README
    force: yes


### Ingress Proxy directory

- name: Create a directory to mount in ingress-proxy container
  file:
    path: "/var/containers/{{ module_id }}/ingress-proxy"
    state: directory
    mode: '0755'

### Ingress Proxy - Certbot data directories

- name: Create a directory to mount for certbot data
  file:
    path: "/var/containers/{{ module_id }}/ingress-proxy/certbot"
    state: directory
    mode: '0755'


### Ingress Proxy - TLS certificates directories

- name: Create a directory to mount in containers needing TLS certificates
  file:
    path: "/var/containers/{{ module_id }}/ingress-proxy/tls"
    state: directory
    mode: '0755'

- name: Create a directory to mount in containers needing concatenated TLS certificates
  file:
    path: "/var/containers/{{ module_id }}/ingress-proxy/tls/concatenated"
    state: directory
    mode: '0755'

- name: Create a directory to mount in containers needing non-concatenated TLS certificates
  file:
    path: "/var/containers/{{ module_id }}/ingress-proxy/tls/non-concatenated"
    state: directory
    mode: '0755'
