---
# SPDX-FileCopyrightText: 2022 Wilfred Nicoll <xyzroller@rollyourown.xyz>
# SPDX-License-Identifier: GPL-3.0-or-later


# Copy nftables configuration
#
- name: Copy nftables configuration
  template:
    mode: 0770
    owner: root
    group: root
    dest: /etc/nftables.conf
    src: nftables.conf.j2
    force: yes


# Copy nftables reload script
#
- name: Copy nftables reload script
  copy:
    mode: 0770
    owner: root
    group: root
    dest: /usr/local/bin/reload-nftables.sh
    src: reload-nftables.sh
    force: yes
