---

# Create directory for consul-template configuration files
#
- name: Create directory for consul-template configuration files
  file:
    path: /etc/consul-template
    state: directory
    mode: 0755


# Copy consul-template configuration file
#
- name: Copy consul-template configuration file
  copy:
    mode: 0644
    owner: root
    group: root
    dest: /etc/consul-template/consul-template-config.hcl
    src: consul-template-config.hcl
    force: yes


# Copy consul-template template file for dynamic certbot initialisation based on consul key-values
#
- name: Copy consul-template template file for dynamic certbot initialisation
  copy:
    mode: 0644
    owner: root
    group: root
    dest: /etc/consul-template/certbot-initialise.ctmpl
    src: certbot-initialise.ctmpl
    force: yes


# Create a mount directory for non-concatenated certificates 
#
- name: Create a mount directory for non-concatenated certificates
  file:
    path: /var/certs
    state: directory
    mode: 0755


# Copy consul-template template file for dynamic cert deployment script based on consul key-values
#
- name: Copy consul-template template file for dynamic cert deployment
  copy:
    mode: 0644
    owner: root
    group: root
    dest: /etc/consul-template/cert-deploy.ctmpl
    src: cert-deploy.ctmpl
    force: yes


# Copy consul-template template file for dynamic iptables configuration based on consul key-values
#
- name: Copy consul-template template file for dynamic iptables configuration
  copy:
    mode: 0644
    owner: root
    group: root
    dest: /etc/consul-template/iptables-rules.ctmpl
    src: iptables-rules.ctmpl
    force: yes


# Copy consul-template template file for dynamic haproxy configuration based on consul key-values and service discovery
#
- name: Copy consul-template template file for dynamic haproxy configuration
  copy:
    mode: 0644
    owner: root
    group: root
    dest: /etc/consul-template/haproxy.ctmpl
    src: haproxy.ctmpl
    force: yes


# Copy consul-template service definition
#
- name: Copy consul-template service definition
  copy:
    mode: 0644
    owner: root
    group: root
    dest: /lib/systemd/system/consul-template.service
    src: consul-template.service
    force: yes


# Enable consul-template service
#
- name: Enable consul-template service
  service:
    name: consul-template.service
    enabled: yes
    state: stopped
