---
# SPDX-FileCopyrightText: 2022 Wilfred Nicoll <xyzroller@rollyourown.xyz>
# SPDX-License-Identifier: GPL-3.0-or-later

- name: Make sure certbot packages are uninstalled and purged
  apt:
    name: certbot
    update_cache: no
    purge: yes
    state: absent


- name: Make sure snapd is installed
  apt:
    name: snapd
    update_cache: yes
    state: present


- name: Install certbot snap package
  snap:
    name: certbot
    classic: yes
    state: present


- name: Prepare the Certbot command
  file:
    src: /snap/bin/certbot
    dest: /usr/bin/certbot
    state: link


- name: Create the letsencrypt configuration directory
  file:
    path: /etc/letsencrypt
    state: directory
    mode: '0755'
