---
- name: Copy self-signed cert to mount directory for haproxy ssl
  copy:
    mode: 0640
    owner: root
    group: root
    dest: /var/containers/{{ module_id }}/ingress-proxy/tls/concatenated/ryo.pem
    src: ryo.pem
    force: yes

- name: Copy self-signed non-concatenated cert to mount directory for haproxy ssl
  copy:
    mode: 0640
    owner: root
    group: root
    dest: /var/containers/{{ module_id }}/ingress-proxy/tls/non-concatenated/ryo.cert.pem
    src: ryo.cert
    force: yes

- name: Copy self-signed non-concatenated key to mount directory for haproxy ssl
  copy:
    mode: 0640
    owner: root
    group: root
    dest: /var/containers/{{ module_id }}/ingress-proxy/tls/non-concatenated/ryo.key.pem
    src: ryo.key
    force: yes
