---
# SPDX-FileCopyrightText: 2022 Wilfred Nicoll <xyzroller@rollyourown.xyz>
# SPDX-License-Identifier: GPL-3.0-or-later


# Create webhook working directory
#
- name: Create webhook working directory
  file:
    path: /var/webhook
    state: directory
    mode: '0755'


# Copy webhook configuration
#
- name: Copy webhook configuration
  copy:
    mode: 0660
    owner: root
    group: root
    dest: /usr/local/bin/hooks.yaml
    src: hooks.yaml
    force: yes


# Copy webhook start script
#
- name: Copy webhook start script
  copy:
    mode: 0770
    owner: root
    group: root
    dest: /usr/local/bin/start-webhook.sh
    src: start-webhook.sh
    force: yes


# Copy webhook service definition
#
- name: Copy webhook service definition
  copy:
    mode: 0644
    owner: root
    group: root
    dest: /lib/systemd/system/webhook.service
    src: webhook.service
    force: yes


#Enable webhook service
#
- name: Enable webhook service
  service:
    name: webhook.service
    enabled: yes
    state: started


# Copy webhook haproxy-reload consul service configuration file
#
- name: Copy webhook haproxy-reload consul service configuration file
  copy:
    mode: 0640
    owner: consul
    group: consul
    dest: /etc/consul.d/haproxy-reload-service.hcl
    src: haproxy-reload-service.hcl
    force: yes
