---
# SPDX-FileCopyrightText: 2022 Wilfred Nicoll <xyzroller@rollyourown.xyz>
# SPDX-License-Identifier: GPL-3.0-or-later


# Copy empty certbot initialisation and deployment scripts (making executable)
#
- name: Copy certbot initialisation script
  copy:
    mode: 0770
    owner: root
    group: root
    dest: /usr/local/bin/certbot-initialise.sh
    src: certbot-initialise.sh
    force: yes

- name: Copy certbot deployment script
  copy:
    mode: 0770
    owner: root
    group: root
    dest: /usr/local/bin/cert-deploy.sh
    src: cert-deploy.sh
    force: yes
